# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190109_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(max_length=20),
        ),
    ]
