# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190111_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publish_time',
            new_name='create_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.AddField(
            model_name='expression',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expressionimage',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
