# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-11 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190111_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionimage',
            name='article_id',
        ),
        migrations.AddField(
            model_name='expressionimage',
            name='expression_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Expression'),
        ),
    ]
