# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-11 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190111_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionimage',
            name='expression_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Expression'),
        ),
    ]
